name: curiosity
description: Trying out an atomic os for the first time.

base-image: ghcr.io/blue-build/base-images/fedora-base-nvidia-open
image-version: latest 

modules:
  - type: script
    snippets:
      - |
        echo "fastestmirror=True" >> /etc/dnf/dnf.conf
        echo "max_parallel_downloads=10" >> /etc/dnf/dnf.conf

  - type: dnf
    repos:
      copr:
        - sdegler/hyprland
        - avengemedia/danklinux
        - deltacopy/darkly
        - brycensranch/gpu-screen-recorder-git
        - lihaohong/yazi
        - xabi08/MSI-EC
    install:
      packages:
        - yazi
        - msi-ec-kmod
        - gpu-screen-recorder
        - neovim
        - atuin
        - gh
        - mpd
        - mpv
        - ffmpeg
        - cava
        - pavucontrol
        - wireplumber
        - libdbusmenu-gtk3-devel
        - playerctl
        - geoclue2
        - bsdtar
        - brightnessctl
        - ddcutil
        - bc
        - coreutils
        - cliphist
        - cmake
        - curl
        - wget2
        - ripgrep
        - jq
        - xdg-utils
        - rsync
        - yq
        - adw-gtk3-theme
        - darkly
        - eza
        - fish
        - fontconfig
        - kitty
        - material-icons-fonts
        - twitter-twemoji-fonts
        - hyprland
        - hyprland-guiutils
        - hyprland-qt-support
        - hyprsunset
        - wl-clipboard
        - bluedevil
        - gnome-keyring
        - plasma-nm
        - plasma-integration-qt5
        - plasma-integration
        - polkit-kde
        - dolphin
        - nemo
        - plasma-systemsettings
        - xdg-desktop-portal
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-kde
        - xdg-desktop-portal-hyprland
        - clang
        - uv
        - gtk4-devel
        - libadwaita-devel
        - libsoup3-devel
        - libportal-gtk4
        - gobject-introspection-devel
        - python3
        - python3.12
        - python3-devel
        - python3.12-devel
        - quickshell-git
        - matugen
        - hyprshot
        - slurp
        - swappy
        - tesseract
        - tesseract-langpack-eng
        - wf-recorder
        - upower
        - wtype
        - ydotool
        - fuzzel
        - glib2
        - ImageMagick
        - hypridle
        - hyprlock
        - hyprpicker
        - translate-shell
        - qalculate
        - wlogout
        - unzip
        - firefox
        - sddm
        - ffmpegthumbnailer
        - bat
        - fzf 
        - ripgrep
        - qt6-qtpositioning
        - breeze-icon-theme
        - kf6-breeze-icons
        - p7zip
        - p7zip-plugins 
        - android-tools
        - aria2
        - atuin
        - bat
        - blueman
        - btop 
        - celluloid
        - evtest
        - fzf
        - gdu
        - papirus-icon-theme
        - power-profiles-daemon
        - stow 
        - usbip
        - wireguard-tools
        - zoxide
        - obs-studio
        - mediawriter
        - tealdeer
        - usbutils
        - pciutils
        - inxi
        - lshw
        - lm_sensors
        - smartmontools
        - nvtop
        - iputils
        - bind-utils
        - nmap
        - traceroute
        - iproute
        - fd-find
        - tree
        - gamemode
        - gamescope


  - type: default-flatpaks
    configurations:
      - notify: false
      - scope: user
        install:
          - org.freedownloadmanager.Manager
          - com.github.johnfactotum.Foliate
          - io.github.celluloid_player.Celluloid
          - org.vinegarhq.Sober
          - com.spotify.Client
          - com.usebottles.bottles
      - scope: system

  - type: script
    scripts:
      - install-rmpc.sh
      - install-vesktop.sh 
      - install-opentabletdriver.sh
      - install-mpvpaper.sh
      - install-openclaw.sh
      - install-mpd-mpris.sh
      - install-gogcli.sh
      - install-mcontrolcenter.sh

  - type: systemd
    system:
      enabled:
        - ydotool 
        - power-profiles-daemon
    user:
      enabled:
        - opentabletdriver
        - mpd 
        - mpd-mpris
