#!/bin/bash
GUEST_NAME="$1"
HOOK_NAME="$2"
STATE_NAME="$3"

if [ "$GUEST_NAME" == "win11" ]; then
    if [ "$HOOK_NAME" == "prepare" ] && [ "$STATE_NAME" == "begin" ]; then
        # Banish Linux to E-cores (Threads 8-11)
        systemctl set-property --runtime -- system.slice AllowedCPUs=8-11
        systemctl set-property --runtime -- user.slice AllowedCPUs=8-11
        systemctl set-property --runtime -- init.scope AllowedCPUs=8-11
	systemctl start smb
        
        # Compact memory and allocate 4096 Hugepages (8GB)
        # echo 1 > /proc/sys/vm/compact_memory
        # sleep 1
        # echo 4096 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
    fi

    if [ "$HOOK_NAME" == "release" ] && [ "$STATE_NAME" == "end" ]; then
        # Release Linux back to all cores (Threads 0-11)
        systemctl set-property --runtime -- system.slice AllowedCPUs=0-11
        systemctl set-property --runtime -- user.slice AllowedCPUs=0-11
        systemctl set-property --runtime -- init.scope AllowedCPUs=0-11
	systemctl stop smb
        
        # Deallocate Hugepages
        # echo 0 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
    fi
fi

