[Unit]
# Clear the Red Hat dracut condition since Arch mkinitcpio doesn't create it
ConditionPathExists=

[Timer]
# Clear any and all default schedules
OnCalendar=
OnBootSec=
OnUnitInactiveSec=

# Set exactly one trigger: 15 minutes after boot
OnBootSec=15min
