[global]
   workgroup = WORKGROUP
   server string = CachyOS Host
   security = user
   map to guest = bad user
   
   # Performance tweaks for VM to Host speed!
   socket options = TCP_NODELAY IPTOS_LOWDELAY
   read raw = yes
   write raw = yes

[Games]
   path = /var/home/zei/Games
   acl allow execute always = yes
   browsable = yes
   writable = yes
   valid users = zei
