# ZRAM Aggressive Swappiness
vm.swappiness = 180
vm.watermark_scale_factor = 125
vm.watermark_boost_factor = 0
vm.page-cluster = 0

# Network: BBRv3 Congestion Control
net.ipv4.tcp_congestion_control = bbr

# Network: CAKE Queue Discipline (Bufferbloat Killer)
net.core.default_qdisc = cake

# Network: TCP Fast Open (0 = disabled, 3 = enabled for both incoming/outgoing)
net.ipv4.tcp_fastopen = 3

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
