name: bluebuild
on:
  schedule:
    - cron:
        "17 21 * * *" # build at 02:47 IST, (21:17 UTC)
  push:
    paths-ignore: 
      - "**.md"

  pull_request:
  workflow_dispatch: 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false 
      matrix:
        recipe:
          - recipe.yml
    steps:
      - name: Notify Build Started
        run: |
          curl -d "Building Curiosity OS..." \
          -H "Title: GitHub Actions" \
          -H "Priority: default" \
          -H "Tags: hammer_and_wrench" \
          ntfy.sh/${{ secrets.NTFY_TOPIC }}

      - name: Build Custom Image
        uses: blue-build/github-action@v1.12
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        with:
          recipe: ${{ matrix.recipe }}
          build_opts: "--no-sign"
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          use_cache: true

      - name: Notify Build Success
        if: success()
        run: |
          curl -d "SUCCESS" \
          -H "Title: Build Complete!" \
          -H "Priority: high" \
          -H "Tags: white_check_mark" \
          ntfy.sh/${{ secrets.NTFY_TOPIC }}

      - name: Notify Build Failed
        if: failure()
        run: |
          curl -d "FAILED" \
          -H "Title: Build Crashed!" \
          -H "Priority: urgent" \
          -H "Tags: warning" \
          ntfy.sh/${{ secrets.NTFY_TOPIC }}
